export const umraTours = [
  {
    category: "lux",
    travelCompany: "HajjTravel",
    price: 500000,
    duration: 7,
    hotel: "Mariot",
    meals: true,
    description: "",
  },
  {
    category: "standart",
    travelCompany: "PavlodarTravel",
    price: 300000,
    duration: 7,
    hotel: "Mariot",
    meals: false,
    description: "",
  },
  {
    category: "comfort",
    travelCompany: "HajjTravel",
    price: 530000,
    duration: 10,
    hotel: "Mariot",
    meals: true,
    description: "",
  },
  {
    category: "comfort",
    travelCompany: "PavlodarTravel",
    price: 580000,
    duration: 7,
    hotel: "Movenpick",
    meals: true,
    description: "",
  },
  {
    category: "premium",
    travelCompany: "IslamTravel",
    price: 700000,
    duration: 7,
    hotel: "Hayat",
    meals: true,
    description: "",
  },
  {
    category: "standart",
    travelCompany: "IslamTravel",
    price: 500000,
    duration: 14,
    hotel: "Hotel",
    meals: false,
    description: "",
  },
  {
    category: "standart",
    travelCompany: "HajjTravel",
    price: 500000,
    duration: 7,
    hotel: "Mariot",
    meals: true,
    description: "",
  },
];
